disabled = false
languageCode = "pt"
contentDir = "content/pt"
languageName = "Português (Brasil)" # Nome que aparecerá no seletor de idiomas
weight = 1                        # Se 'en' é 1, 'pt-BR' pode ser 2 para definir a ordem

title = "Gamificação ORG"        # Título do site em PT-BR (pode ser o mesmo ou traduzido/localizado)

[params]
  displayName = "PT"              # Nome curto para o seletor de idiomas (ex: PT ou PT-BR)
  isoCode = "pt"               # Código ISO para pt-BR
  rtl = false                     # Português não é da direita para a esquerda
  dateFormat = "02/01/2006" # Formato de data em português (Go layout)
  logo = "logo.png"               # Caminho para o logo (geralmente o mesmo)
  # Outros params específicos do tema que você queira traduzir ou ajustar para pt-BR
  # Por exemplo, se você tiver um 'description' em params no 'en', adicione a versão pt-BR aqui.

  [params.author]
    name = "CEDIS" 
