[[main]]
name = "Sobre"
pre = "eye"
pageRef = "about"
identifier = "OmXIR5znfN"
weight = 10

[[main]]
name = "Reuniões"
pre = "list"
pageRef = "reunioes"
identifier = "meetings-pt"
weight = 20

[[main]]
name = "Pessoas"
pre = "graduation-cap"
pageRef = "pessoas"
identifier = "people-pt"
weight = 30

[[footer]]
name = "GitHub"
url = "https://github.com/CedisUnB"
identifier = "STHwfSjXAO"
weight = 9_999
