[[main]]
none = "none"

[[main]]
name = "Sobre"
pre = "eye"
pageRef = "about"
identifier = "OmXIR5znfN"
weight = 9_999

[[main]]
name = "Reuniões"
pre = "list"
pageRef = "reunioes"
identifier = "meetings-pt"
weight = 9_999

[[main]]
name = "Pessoas"
pre = "graduation-cap"
pageRef = "pessoas"
identifier = "people-pt"
weight = 9_999

[[footer]]
none = "none"

[[footer]]
pageRef = "https://github.com/CedisUnB"
identifier = "STHwfSjXAO"
weight = 9_999
