[[main]]
name = "Sobre"
pre = "eye"
pageRef = "about"
identifier = "OmXIR5znfN"
weight = 10

[[main]]
name = "Reuniões"
pre = "list"
pageRef = "reunioes"
identifier = "meetings-pt"
weight = 20

#[[main]]
#name = "Pessoas"
#pre = "graduation-cap"
#pageRef = "pessoas"
#identifier = "people-pt"
#weight = 30

[[main]]
name = "Integrantes"
pre = "user"
pageRef = "integrantes"
identifier = "members-pt"
weight = 35

[[main]]
name = "Produções"
pre = "pencil"
pageRef = "producoes"
identifier = "productions-pt"
weight = 40

[[main]]
name = "Parcerias"
pre = "link"
pageRef = "parcerias"
identifier = "partnerships-pt"
weight = 50

[[footer]]
name = "GitHub"
url = "https://github.com/CedisUnB"
identifier = "STHwfSjXAO"
weight = 9_999
