[[main]]
name = "About"
pre = "eye"
pageRef = "about"
identifier = "OmXIR5znfN"
weight = 10

[[main]]
name = "Meetings"
pre = "list"
pageRef = "meetings"
identifier = "meetings-en"
weight = 20

[[main]]
name = "People"
pre = "graduation-cap"
pageRef = "people"
identifier = "people-en"
weight = 30

[[main]]
name = "Productions"
pre = "pencil"
pageRef = "productions"
identifier = "productions-en"
weight = 40

[[main]]
name = "Partnerships"
pre = "link"
pageRef = "partnerships"
identifier = "partnerships-en"
weight = 50

[[footer]]
name = "GitHub"
url = "https://github.com/CedisUnB"
identifier = "STHwfSjXAO"
weight = 9_999
